services:
  db:
    image: postgres:15-alpine
    container_name: jira-db
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: jira-server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jira
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: jira-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources:/opt/jirarush/resources:ro
    restart: unless-stopped

volumes:
  pgdata:
